version: '3'

services:
  gis4dis-backend:
    image: bulva/gis4dis-backend:latest
    build: .
    volumes:
      - .:/opt/services/gis4dis-backend/src
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/yourdomain.pem:/etc/ssl/yourdomain.pem
      - ./config/nginx/yourdomain.key:/etc/ssl/yourdomain.key
    depends_on:
      - gis4dis-backend
    networks:
      - nginx_network

  database:
    image: kartoza/postgis:11.0-2.5
    env_file:
      - config/db/database_env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data
      - ./data/rest_11-02-2019.sql:/rest_11-02-2019.sql

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge

volumes:
  database_volume: