# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-11 19:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetadataObservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('observation_time', models.TimeField()),
                ('observation_time_range', models.TimeField()),
                ('send_date', models.DateTimeField()),
                ('municipality', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('note', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PhenomenonParameterValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Parameter')),
            ],
        ),
        migrations.RemoveField(
            model_name='helppictures',
            name='help',
        ),
        migrations.RemoveField(
            model_name='observationphenomenon',
            name='drought',
        ),
        migrations.RemoveField(
            model_name='observationphenomenon',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observationphenomenon',
            name='phenomenon',
        ),
        migrations.RenameField(
            model_name='help',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='help',
            name='title',
        ),
        migrations.RemoveField(
            model_name='phenomenon',
            name='phenomenon',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='education_field',
        ),
        migrations.AddField(
            model_name='phenomenon',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Drought',
        ),
        migrations.DeleteModel(
            name='HelpPictures',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='ObservationPhenomenon',
        ),
        migrations.AddField(
            model_name='phenomenonparametervalue',
            name='phenomenon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Phenomenon'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='phenomenon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Phenomenon'),
        ),
        migrations.AddField(
            model_name='metadataobservation',
            name='value',
            field=models.ManyToManyField(to='api.PhenomenonParameterValue'),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Parameter'),
        ),
        migrations.AddField(
            model_name='phenomenon',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.Category'),
            preserve_default=False,
        ),
    ]
