# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-12 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171012_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='text',
            field=models.TextField(max_length=4096),
        ),
    ]
