# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-13 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171012_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadataobservation',
            old_name='value',
            new_name='values',
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Parameter'),
        ),
    ]
