# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171014_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataobservation',
            name='values',
        ),
        migrations.AddField(
            model_name='metadataobservation',
            name='values',
            field=models.ManyToManyField(to='api.PhenomenonParameterValue'),
        ),
    ]
