# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171014_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='phenomenonparametervalue',
            name='image',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
