# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-14 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_phenomenonparametervalue_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataobservation',
            name='observation_time_range',
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='send_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='phenomenonparametervalue',
            name='image',
            field=models.ImageField(max_length=255, upload_to='photos'),
        ),
    ]
