# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171014_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataobservation',
            name='municipality',
        ),
    ]
