# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 16:38
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_metadataobservation_municipality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadataobservation',
            name='location',
        ),
        migrations.AddField(
            model_name='metadataobservation',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='', srid=4326),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='note',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='observation_time',
            field=models.TimeField(blank=True),
        ),
    ]
