# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 16:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171016_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataobservation',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
