# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-16 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20171016_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataobservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='note',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='metadataobservation',
            name='observation_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
