# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-10-18 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20171016_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenomenonparametervalue',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='photos'),
        ),
    ]
