# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-06 22:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20171018_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhenomenonPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='photos')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='phenomenonparametervalue',
            name='image',
        ),
        migrations.AddField(
            model_name='phenomenonparametervalue',
            name='image',
            field=models.ManyToManyField(to='api.PhenomenonPhoto'),
        ),
    ]
