# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-06 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180106_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phenomenonparametervalue',
            name='image',
        ),
        migrations.AddField(
            model_name='phenomenonphoto',
            name='parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.PhenomenonParameterValue'),
            preserve_default=False,
        ),
    ]
