# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-06 22:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180106_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phenomenonphoto',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phenomenonphoto',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.PhenomenonParameterValue'),
        ),
    ]
