# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-01-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180106_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education',
            field=models.CharField(choices=[('0', 'bez vzdělání'), ('1', 'neúplné základní vzdělání'), ('2', 'základní vzdělání'), ('3', 'střední vzdělání')], max_length=128),
        ),
    ]
